### ISSUE TITLE
Rpi cannot connet to the internet

### ISSUE THREAD

**Issue by saxon17** [DesktopContainers/raspberrypi#5]
any method to make it pass?

**Comment by MarvAmBass** [comment]
I Saxon, as far as I remember I had no troubles connecting to the internet when I created this container.

Maybe it's your network setup - maybe something changed over time and it no longer works.

unfortunately I don't have time to investigate this. But if you find a solution I'm happy to merge a fix

**Comment by saxon17** [comment]
remote: Permission to nachoparker/qemu-raspbian-network.git denied to saxon17.
I fixed it by using linux bridge.    and I would like to push  that.

fatal: could not create work tree dir 'raspberrypi': Permission denied

Reference 
https://github.com/nachoparker/qemu-raspbian-network

**Comment by MarvAmBass** [comment]
just tested my container - network / internet access works without any problems when used as I described in my Readme.md.

Keep in mind, if you build this container yourself you might get new versions which are no longer working as my container which is already more than one year old.

I'd recommend to just use my working container `desktopcontainers/raspberrypi` which can be trusted since it's an automated build
